name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - run: go env

    - name: Lint
      uses: golangci/golangci-lint-action@v3

    - name: Vet lint
      run: go vet ./...

    - name: Build binary
      run: make build

    - name: Build docker image
      run: make docker
