name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=vendor
      GOPROXY: "off"

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - run: go env

    - name: Build binary
      run: GOFLAGS="-mod=mod" GOPROXY="https://proxy.golang.org,direct" make build

    - name: Build docker image
      run: make docker
